AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - "test/dummy/db/schema.rb"
    - "bin/*"

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "*.gemspec"

Naming/FileName:
  Exclude:
    - "Gemfile"
    - "Rakefile"
    - "test/dummy/Rakefile"
    - "*.gemspec"

Layout/EndOfLine:
  Enabled: false

Style/AsciiComments:
  Enabled: false
